baseURL = "https://twosix.software/"
languageCode = "en-us"
title = "Two-Six"
[Params]
  description = "Two-Six Portfolio"
  [Params.Terminal]
  schema = "gruvbox_light"

  userName = "two-six"
  pcName = "Emacs"
  workDir = "portfolio"
  profile = "profile.org"

  ps1Delay = 0
  stdoutDelay = 0
  commandDelay = 50

  # Note: speed at which text is displayed on the activity pages
  # Note: if set to 0, typing animation will be disabled
  # Note:
  # Note: if you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  titleDelay = 0 # title speed : "title" in front matter
  contentDelay = 0 # content speed : content in .md file

  description = """
  Hello, I'm two-six 🐱
  I usually work with Bash but I
  also like to use C/C++ or Rust.
  """

  [Params.Tree]
  use = true
  folderName = "Personal\\ Pages"
  files = [
    ["Github", "https://github.com/two-six"],
    ["Twitter", "https://twitter.com/two_six_26"]
  ]
